drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    login_id varchar(100) unique,
    password varchar(100),
    name varchar(100),
    age integer,
    primary key (id)
);